// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SpaceGame.Data;
using SpaceGame.Data.Models;
using System;

namespace SpaceGame.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpaceGame.Data.Models.Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("HostPlayerId");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsInGame");

                    b.Property<string>("Name");

                    b.Property<DateTime>("StartTime");

                    b.HasKey("Id");

                    b.HasIndex("HostPlayerId");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("SpaceGame.Data.Models.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("GroupId");

                    b.Property<long?>("GroupId1");

                    b.Property<string>("Name");

                    b.Property<int?>("Role");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("GroupId1");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("SpaceGame.Data.Models.Group", b =>
                {
                    b.HasOne("SpaceGame.Data.Models.Player", "HostPlayer")
                        .WithMany()
                        .HasForeignKey("HostPlayerId");
                });

            modelBuilder.Entity("SpaceGame.Data.Models.Player", b =>
                {
                    b.HasOne("SpaceGame.Data.Models.Group")
                        .WithMany("Clients")
                        .HasForeignKey("GroupId");

                    b.HasOne("SpaceGame.Data.Models.Group")
                        .WithMany("Players")
                        .HasForeignKey("GroupId1");
                });
#pragma warning restore 612, 618
        }
    }
}
